Update test1.yml

diff --git a/.github/workflows/test1.yml b/.github/workflows/test1.yml
--- a/.github/workflows/test1.yml
+++ b/.github/workflows/test1.yml
@@ -1,25 +1,20 @@
-name: Input Workflow
-
-on:
-  workflow_dispatch:
-   inputs:
-    username:
-     description: "enter your name"
-     required: true
-     default: "guest"
-
-
 jobs:
-  greeting_job:
+  build:
     runs-on: ubuntu-latest
-    
-    
     steps:
-      - name: "Step 1"
-        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
-        env:
-          First_Name: sandeep
-          DAY_OF_WEEK: sunday
-          Greeting: Hello
-      - name: print usename
-        run: echo "$github.event.inputs.username"
+      - run: echo " Building the application"
+
+  test:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - run: |
+          echo " Running tests"
+          exit 1   # Force fail for demo (remove this in real workflow)
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: test
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
+    steps:
+      - run: echo " Deploying to Production (only on push to main and if tests passed)"
